import type {
  MedMathCategory,
  MedMathDifficulty,
  QuestionKind,
  QuestionResponseType,
  QuestionTemplate,
} from "../types.ts";
import { ANTICOAGULANT_FACTS, INSULIN_FACTS } from "../medication-facts.ts";

interface KnowledgeSpec {
  id: string;
  category: MedMathCategory;
  subtype: string;
  difficulty: MedMathDifficulty;
  title: string;
  scenario: string;
  prompt: string;
  options: string[];
  correct: number | number[];
  explanation: string;
  pearl: string;
  tags: string[];
  kind?: QuestionKind;
}

function makeKnowledgeTemplate(spec: KnowledgeSpec): QuestionTemplate {
  const responseType: QuestionResponseType = Array.isArray(spec.correct)
    ? "select-all"
    : "multiple-choice";
  const correctAnswer = Array.isArray(spec.correct)
    ? spec.correct.reduce((mask, index) => mask | (1 << index), 0)
    : spec.correct;
  const correctLabels = (Array.isArray(spec.correct) ? spec.correct : [spec.correct])
    .map((index) => spec.options[index]);

  return {
    id: spec.id,
    category: spec.category,
    subtype: spec.subtype,
    difficulty: spec.difficulty,
    title: spec.title,
    clinicalContext: "Adult nursing medication education",
    generate: () => ({
      scenario: spec.scenario,
      orderText: "Apply medication knowledge and nursing safety principles.",
      prompt: spec.prompt,
      correctAnswer,
      answerUnit: "choice",
      answerPrecision: 0,
      responseType,
      questionKind: spec.kind ?? "knowledge",
      options: spec.options.map((label, index) => ({ id: String(index), label })),
      correctAnswerLabel: correctLabels.join("; "),
      tags: spec.tags,
      safetyPearl: spec.pearl,
      hints: [
        `Focus on ${spec.tags.slice(0, 2).join(" and ")}.`,
        "Separate the medication's action from the nursing monitoring priority.",
        `Eliminate choices that conflict with this safety principle: ${spec.pearl}`,
      ],
      solutionSteps: [
        {
          stepNumber: 1,
          title: "Clinical reasoning",
          calculation: correctLabels.join("; "),
          explanation: spec.explanation,
          result: correctLabels.join("; "),
        },
        {
          stepNumber: 2,
          title: "Safety pearl",
          calculation: "",
          explanation: spec.pearl,
          result: "Apply the safety check before administration.",
        },
      ],
      rawVariables: { correctOptionIndexes: spec.correct, tags: spec.tags },
    }),
  };
}

const insulinSpecs: KnowledgeSpec[] = [
  { id:"ins-know-lispro-peak", category:"insulin", subtype:"rapid-acting-timing", difficulty:"intermediate", title:"Lispro Peak Risk Window", scenario:"Lispro is administered at 0730 before breakfast.", prompt:"During which time window is hypoglycemia risk greatest based on the course peak range?", options:["0740 to 0745","0800 to 0900","0930 to 1030","1130 to 1530"], correct:1, explanation:`Rapid-acting insulin peaks about ${INSULIN_FACTS.rapid.peakMinutes[0]} to ${INSULIN_FACTS.rapid.peakMinutes[1]} minutes after administration.`, pearl:"Peak action is the period of greatest hypoglycemia concern.", tags:["lispro","peak","hypoglycemia","timing"], kind:"clinical-application" },
  { id:"ins-know-rapid-meal", category:"insulin", subtype:"rapid-acting-meal-safety", difficulty:"beginner", title:"Rapid Insulin and Meal Availability", scenario:"The nurse is preparing lispro, but the breakfast tray has not arrived.", prompt:"What is the safest immediate action?", options:["Give the lispro now and wait for the tray","Verify the meal is available before giving the dose","Substitute NPH for lispro","Hold all insulin for the day"], correct:1, explanation:"Rapid-acting insulin should be coordinated closely with food intake.", pearl:INSULIN_FACTS.rapid.mealTiming, tags:["lispro","meal timing","hypoglycemia","safety"], kind:"clinical-application" },
  { id:"ins-know-rapid-generics", category:"insulin", subtype:"rapid-acting-identification", difficulty:"beginner", title:"Rapid-Acting Insulin Identification", scenario:"A student reviews common rapid-acting insulin names.", prompt:"Which medication is rapid acting?", options:["Insulin lispro","NPH insulin","Insulin glargine","Insulin degludec"], correct:0, explanation:"Lispro is a rapid-acting insulin analog.", pearl:"Always verify both the generic name and concentration before administration.", tags:["lispro","rapid acting","identification"] },
  { id:"ins-know-aspart-brand", category:"insulin", subtype:"rapid-acting-identification", difficulty:"beginner", title:"Aspart Brand Recognition", scenario:"The medication record lists NovoLog.", prompt:"Which generic insulin is NovoLog?", options:["Aspart","Lispro","Glulisine","Regular insulin"], correct:0, explanation:"NovoLog is a brand of insulin aspart.", pearl:"Brand recognition never replaces checking the insulin label.", tags:["aspart","NovoLog","brand"] },
  { id:"ins-know-glulisine-brand", category:"insulin", subtype:"rapid-acting-identification", difficulty:"beginner", title:"Glulisine Brand Recognition", scenario:"The order lists Apidra.", prompt:"Which generic insulin is Apidra?", options:["Glargine","Glulisine","Degludec","Detemir"], correct:1, explanation:"Apidra is insulin glulisine.", pearl:"Confirm the insulin type before selecting an administration time.", tags:["glulisine","Apidra","brand"] },
  { id:"ins-know-rapid-onset", category:"insulin", subtype:"rapid-acting-timing", difficulty:"beginner", title:"Rapid-Acting Onset", scenario:"A patient receives a rapid-acting insulin analog.", prompt:"Which onset range matches the supplied course reference?", options:["10 to 15 minutes","30 to 60 minutes","2 to 4 hours","4 to 12 hours"], correct:0, explanation:`The course reference lists an onset of about ${INSULIN_FACTS.rapid.onsetMinutes[0]} to ${INSULIN_FACTS.rapid.onsetMinutes[1]} minutes.`, pearl:"Onset is when action begins. Peak is when effect is strongest.", tags:["rapid acting","onset","timing"] },
  { id:"ins-know-regular-peak", category:"insulin", subtype:"regular-insulin-timing", difficulty:"intermediate", title:"Regular Insulin Peak", scenario:"Regular insulin is administered subcutaneously at 0800.", prompt:"When should the nurse monitor most closely for peak-related hypoglycemia?", options:["0810 to 0815","0830 to 0900","1000 to 1100","1600 to 2000"], correct:2, explanation:`Regular insulin peaks about ${INSULIN_FACTS.regular.peakHours[0]} to ${INSULIN_FACTS.regular.peakHours[1]} hours after administration.`, pearl:"Use the medication's peak, not its onset, to identify the highest hypoglycemia-risk window.", tags:["regular insulin","peak","hypoglycemia","timing"], kind:"clinical-application" },
  { id:"ins-know-regular-iv", category:"insulin", subtype:"regular-insulin-safety", difficulty:"beginner", title:"Insulin Route Recognition", scenario:"An adult patient requires an IV insulin infusion under protocol.", prompt:"Which insulin is used for the IV infusion?", options:["Regular insulin","NPH insulin","Insulin glargine","Insulin degludec"], correct:0, explanation:"Regular insulin can be administered intravenously and used for insulin infusions.", pearl:"IV insulin requires a validated protocol, pump programming, and frequent glucose monitoring.", tags:["regular insulin","IV","infusion","safety"] },
  { id:"ins-know-clear-cloudy", category:"insulin", subtype:"insulin-mixing", difficulty:"beginner", title:"Clear Before Cloudy", scenario:"Regular insulin and NPH are prescribed in one syringe.", prompt:"Which insulin should the nurse draw up first?", options:["Cloudy NPH","Clear regular insulin","Either insulin in any order","Glargine first"], correct:1, explanation:INSULIN_FACTS.regular.mixingSequence, pearl:"Clear before cloudy helps prevent contaminating regular insulin with NPH.", tags:["regular insulin","NPH","mixing","clear before cloudy"] },
  { id:"ins-know-nph-appearance", category:"insulin", subtype:"nph-safety", difficulty:"beginner", title:"NPH Appearance", scenario:"The nurse inspects an NPH vial before preparing a dose.", prompt:"Which appearance is expected after gentle resuspension?", options:["Cloudy","Bright red","Completely clear","Blue tinted"], correct:0, explanation:`NPH is an intermediate-acting insulin with a ${INSULIN_FACTS.nph.appearance} appearance.`, pearl:"Do not confuse expected NPH cloudiness with particulate contamination in a normally clear insulin.", tags:["NPH","appearance","cloudy","safety"] },
  { id:"ins-know-nph-peak", category:"insulin", subtype:"nph-timing", difficulty:"intermediate", title:"NPH Peak Window", scenario:"NPH is administered at 0700.", prompt:"Which window matches its approximate peak from the supplied course reference?", options:["0710 to 0715","0730 to 0830","1100 to 1900","2300 to 0700 the next day only"], correct:2, explanation:`NPH peaks about ${INSULIN_FACTS.nph.peakHours[0]} to ${INSULIN_FACTS.nph.peakHours[1]} hours after administration.`, pearl:"Plan glucose monitoring and nutrition around the broad NPH peak window.", tags:["NPH","peak","hypoglycemia","timing"], kind:"clinical-application" },
  { id:"ins-know-nph-class", category:"insulin", subtype:"nph-identification", difficulty:"beginner", title:"NPH Classification", scenario:"The nurse reviews the insulin profile before administration.", prompt:"How is NPH classified?", options:["Rapid acting","Short acting","Intermediate acting","Ultra-long acting"], correct:2, explanation:"NPH is intermediate acting.", pearl:"Classification helps connect onset, peak, and duration to bedside risk.", tags:["NPH","intermediate acting","classification"] },
  { id:"ins-know-glargine-mix", category:"insulin", subtype:"long-acting-safety", difficulty:"beginner", title:"Glargine Mixing Safety", scenario:"The patient has orders for glargine and lispro at the same medication pass.", prompt:"Which action is correct?", options:["Mix both in one syringe","Mix glargine only with NPH","Administer glargine separately","Draw glargine first, then lispro"], correct:2, explanation:INSULIN_FACTS.longActing.glargineMixing, pearl:"Glargine must not be diluted or mixed with another insulin or solution.", tags:["glargine","mixing","safety"] },
  { id:"ins-know-long-peak", category:"insulin", subtype:"long-acting-timing", difficulty:"beginner", title:"Long-Acting Peak Profile", scenario:"The nurse teaches a patient about basal insulin glargine.", prompt:"Which action profile is expected?", options:["A pronounced peak at 30 minutes","A pronounced peak at 2 hours","Minimal or no pronounced peak","No glucose-lowering action"], correct:2, explanation:INSULIN_FACTS.longActing.peak, pearl:"A flat profile does not eliminate hypoglycemia risk.", tags:["glargine","long acting","peak"] },
  { id:"ins-know-degludec-class", category:"insulin", subtype:"ultra-long-identification", difficulty:"beginner", title:"Degludec Classification", scenario:"The medication list includes Tresiba.", prompt:"Which insulin type is Tresiba (degludec)?", options:["Rapid acting","Short acting","Intermediate acting","Ultra-long acting"], correct:3, explanation:"Degludec is an ultra-long-acting basal insulin.", pearl:"Verify concentrated insulin products and delivery devices carefully.", tags:["degludec","Tresiba","ultra-long"] },
  { id:"ins-know-toujeo", category:"insulin", subtype:"ultra-long-identification", difficulty:"intermediate", title:"Glargine U-300 Recognition", scenario:"The medication record lists Toujeo.", prompt:"Which description is correct?", options:["Rapid-acting lispro U-100","Intermediate NPH","Ultra-long glargine U-300","Regular insulin for IV infusion"], correct:2, explanation:"Toujeo is insulin glargine U-300 with a prolonged basal profile.", pearl:"Never assume all glargine products have the same concentration.", tags:["Toujeo","glargine U-300","concentration"] },
  { id:"ins-know-u100", category:"insulin", subtype:"insulin-concentration", difficulty:"beginner", title:"U-100 Interpretation", scenario:"A vial is labeled U-100 insulin.", prompt:"What concentration does U-100 indicate?", options:["10 units/mL","50 units/mL","100 units/mL","500 units/mL"], correct:2, explanation:`U-100 contains ${INSULIN_FACTS.concentration.u100UnitsPerMl} units per mL.`, pearl:"Match the ordered units, insulin concentration, and delivery device.", tags:["U-100","concentration","units per mL"] },
  { id:"ins-know-peak-meaning", category:"insulin", subtype:"insulin-timing-concepts", difficulty:"beginner", title:"Meaning of Peak", scenario:"A student compares onset, peak, and duration.", prompt:"What does peak describe?", options:["When the medication first begins working","When the medication effect is strongest","How long the vial remains open","When the medication is eliminated completely"], correct:1, explanation:"Peak is the period of strongest medication effect.", pearl:"For insulin, the peak commonly identifies the greatest hypoglycemia concern.", tags:["peak","onset","duration","hypoglycemia"] },
  { id:"ins-know-duration-meaning", category:"insulin", subtype:"insulin-timing-concepts", difficulty:"beginner", title:"Meaning of Duration", scenario:"A student reviews an insulin action profile.", prompt:"What does duration describe?", options:["Time until action begins","Time of strongest effect","Approximate length of action","Time needed to draw up the dose"], correct:2, explanation:"Duration is the approximate length of the medication's action.", pearl:"Onset, peak, and duration answer different clinical questions.", tags:["duration","onset","peak"] },
  { id:"ins-know-missed-meal", category:"insulin", subtype:"rapid-acting-meal-safety", difficulty:"intermediate", title:"Rapid Insulin Without a Meal", scenario:"Lispro was administered, and the meal tray is unexpectedly delayed.", prompt:"What is the priority concern?", options:["Hypertension","Hypoglycemia","Hyperkalemia","Constipation"], correct:1, explanation:"Rapid insulin can lower glucose before carbohydrate is available.", pearl:"Assess glucose and obtain a carbohydrate source per facility protocol when a meal is delayed.", tags:["lispro","meal delay","hypoglycemia","priority"], kind:"clinical-application" },
  { id:"ins-know-bg-check", category:"insulin", subtype:"insulin-administration-safety", difficulty:"beginner", title:"Pre-Administration Safety Check", scenario:"The nurse prepares a scheduled insulin dose.", prompt:"Which assessment is essential before selecting the dose?", options:["Current blood glucose and the active order","Patient's height only","Last month's weight only","Room temperature"], correct:0, explanation:"The current glucose and active medication order guide safe insulin dose selection.", pearl:"Verify the insulin name, concentration, dose, route, timing, and current glucose.", tags:["blood glucose","dose selection","safety"] },
  { id:"ins-know-double-check", category:"insulin", subtype:"insulin-administration-safety", difficulty:"intermediate", title:"Insulin Dose Verification", scenario:"A high-alert medication policy requires an independent check for insulin.", prompt:"What should the second nurse independently verify?", options:["Only the patient's room number","The order, insulin product, concentration, dose, and patient","Only the syringe color","Only the meal choice"], correct:1, explanation:"An independent check should cover the elements that can cause a medication error.", pearl:"Follow the facility's high-alert medication verification policy.", tags:["double check","high alert","insulin safety"] },
  { id:"ins-know-regular-nph-sata", category:"insulin", subtype:"insulin-mixing", difficulty:"intermediate", title:"Regular and NPH Safety", scenario:"The nurse will prepare compatible regular and NPH insulin in one syringe.", prompt:"Which statements are correct? Select all that apply.", options:["Regular insulin is clear","NPH insulin is cloudy","Draw NPH before regular","Draw regular before NPH"], correct:[0,1,3], explanation:"Regular insulin is clear, NPH is cloudy, and regular is drawn first.", pearl:"Clear before cloudy.", tags:["regular insulin","NPH","mixing","select all"] },
  { id:"ins-know-rapid-sata", category:"insulin", subtype:"rapid-acting-safety", difficulty:"intermediate", title:"Rapid-Acting Nursing Priorities", scenario:"A patient is scheduled to receive rapid-acting insulin with breakfast.", prompt:"Which actions support safe administration? Select all that apply.", options:["Check the current glucose","Confirm the meal is available","Delay glucose monitoring until tomorrow","Verify the ordered dose"], correct:[0,1,3], explanation:"Current glucose, meal coordination, and order verification reduce error and hypoglycemia risk.", pearl:"Rapid insulin should be tightly coordinated with nutrition and monitoring.", tags:["rapid acting","meal timing","glucose","select all"] },
  { id:"ins-know-regular-onset", category:"insulin", subtype:"regular-insulin-timing", difficulty:"beginner", title:"Regular Insulin Onset", scenario:"Regular insulin is administered subcutaneously.", prompt:"Which approximate onset matches the supplied course reference?", options:["10 to 15 minutes","30 minutes","2 to 4 hours","4 to 12 hours"], correct:1, explanation:`Regular insulin begins acting in about ${INSULIN_FACTS.regular.onsetMinutes[0]} minutes.`, pearl:"Do not confuse regular insulin onset with its 2 to 3 hour peak.", tags:["regular insulin","onset","timing"] },
  { id:"ins-know-regular-duration", category:"insulin", subtype:"regular-insulin-timing", difficulty:"beginner", title:"Regular Insulin Duration", scenario:"The nurse reviews the expected action profile of subcutaneous regular insulin.", prompt:"Which approximate duration matches the course reference?", options:["30 to 90 minutes","2 to 4 hours","3 to 6 hours","12 to 18 hours"], correct:2, explanation:`The course reference lists about ${INSULIN_FACTS.regular.durationHours[0]} to ${INSULIN_FACTS.regular.durationHours[1]} hours.`, pearl:"Use the complete action profile when planning monitoring.", tags:["regular insulin","duration","timing"] },
  { id:"ins-know-nph-duration", category:"insulin", subtype:"nph-timing", difficulty:"beginner", title:"NPH Duration", scenario:"The nurse reviews the action profile of NPH.", prompt:"Which approximate duration matches the supplied course reference?", options:["2 to 4 hours","3 to 6 hours","12 to 18 hours","More than 72 hours"], correct:2, explanation:`NPH duration is about ${INSULIN_FACTS.nph.durationHours[0]} to ${INSULIN_FACTS.nph.durationHours[1]} hours.`, pearl:"The broad NPH peak requires ongoing hypoglycemia awareness.", tags:["NPH","duration","timing"] },
  { id:"ins-know-glargine-route", category:"insulin", subtype:"long-acting-safety", difficulty:"intermediate", title:"Glargine Administration", scenario:"A patient has a basal insulin glargine order.", prompt:"Which administration statement is correct?", options:["Give as an IV push","Administer subcutaneously as ordered and do not mix","Use only in an insulin infusion","Mix with regular insulin to reduce injections"], correct:1, explanation:"Insulin glargine is administered subcutaneously and should not be mixed.", pearl:"Glargine is not used for IV treatment of diabetic ketoacidosis.", tags:["glargine","route","mixing","safety"] },
  { id:"ins-know-timing-compare", category:"insulin", subtype:"insulin-timing-comparison", difficulty:"advanced", title:"Insulin Timing Comparison", scenario:"A nurse compares lispro, regular insulin, NPH, and glargine.", prompt:"Which insulin has the broadest pronounced peak window in the supplied course reference?", options:["Lispro","Regular insulin","NPH","Glargine"], correct:2, explanation:"NPH has a broad approximate peak of 4 to 12 hours. Glargine has minimal or no pronounced peak.", pearl:"The width and timing of the peak shape glucose-monitoring priorities.", tags:["NPH","peak","comparison"] },
  { id:"ins-know-no-pronounced-peak", category:"insulin", subtype:"long-acting-timing", difficulty:"intermediate", title:"No Pronounced Peak", scenario:"The nurse selects the insulin with a basal profile and minimal pronounced peak.", prompt:"Which choice best fits that description?", options:["Lispro","Regular insulin","NPH","Glargine"], correct:3, explanation:"Glargine provides a long basal profile with minimal or no pronounced peak.", pearl:"Patients receiving basal insulin still need monitoring for hypoglycemia.", tags:["glargine","basal","peak"] },
];

const anticoagulantSpecs: KnowledgeSpec[] = [
  { id:"ac-know-heparin-monitor", category:"anticoagulants", subtype:"heparin-lab-monitoring", difficulty:"beginner", title:"Heparin Laboratory Monitoring", scenario:"An adult patient is receiving an IV unfractionated heparin infusion.", prompt:"Which laboratory test is most directly associated with routine protocol monitoring?", options:["PT/INR","aPTT/PTT","Hemoglobin A1c","Serum amylase"], correct:1, explanation:ANTICOAGULANT_FACTS.unfractionatedHeparin.commonMonitoring, pearl:"Follow the institution's heparin protocol and verify whether it uses aPTT or anti-Xa.", tags:["heparin","aPTT","monitoring"] },
  { id:"ac-know-warfarin-monitor", category:"anticoagulants", subtype:"warfarin-lab-monitoring", difficulty:"beginner", title:"Warfarin Laboratory Monitoring", scenario:"An adult patient takes warfarin.", prompt:"Which test is commonly used to monitor therapy?", options:["PT/INR","aPTT only","Platelet aggregation time","Troponin"], correct:0, explanation:`Warfarin is monitored with ${ANTICOAGULANT_FACTS.warfarin.monitoring}.`, pearl:"Interpret the INR against the indication-specific ordered goal and current clinical picture.", tags:["warfarin","PT","INR","monitoring"] },
  { id:"ac-know-heparin-reversal", category:"anticoagulants", subtype:"heparin-reversal", difficulty:"beginner", title:"Heparin Reversal", scenario:"A patient has serious bleeding associated with unfractionated heparin.", prompt:"Which medication is the specific reversal agent?", options:["Vitamin K","Protamine sulfate","Idarucizumab","Naloxone"], correct:1, explanation:`The reversal agent is ${ANTICOAGULANT_FACTS.unfractionatedHeparin.reversal}.`, pearl:"Reversal dosing and monitoring depend on the heparin exposure and facility protocol.", tags:["heparin","protamine","reversal"] },
  { id:"ac-know-warfarin-reversal", category:"anticoagulants", subtype:"warfarin-reversal", difficulty:"beginner", title:"Warfarin Reversal Concept", scenario:"An adult taking warfarin has major bleeding and a markedly elevated INR.", prompt:"Which agent directly restores vitamin K availability?", options:["Protamine sulfate","Vitamin K","Idarucizumab","Insulin"], correct:1, explanation:ANTICOAGULANT_FACTS.warfarin.reversal, pearl:"Major bleeding may require additional reversal products according to an urgent protocol.", tags:["warfarin","vitamin K","reversal","INR"] },
  { id:"ac-know-dabigatran-class", category:"anticoagulants", subtype:"dabigatran-knowledge", difficulty:"beginner", title:"Dabigatran Drug Class", scenario:"The medication record lists dabigatran (Pradaxa).", prompt:"How is dabigatran classified?", options:["Vitamin K antagonist","Direct thrombin inhibitor","Factor Xa inhibitor","Antiplatelet P2Y12 inhibitor"], correct:1, explanation:DABIGATRAN_CLASS(), pearl:"Assess bleeding risk and renal function when caring for a patient taking dabigatran.", tags:["dabigatran","Pradaxa","direct thrombin inhibitor"] },
  { id:"ac-know-dabigatran-reversal", category:"anticoagulants", subtype:"dabigatran-reversal", difficulty:"intermediate", title:"Dabigatran Reversal", scenario:"A patient taking dabigatran has life-threatening bleeding.", prompt:"Which specific reversal agent is associated with dabigatran?", options:["Protamine sulfate","Vitamin K","Idarucizumab","Atropine"], correct:2, explanation:`Dabigatran can be reversed with ${ANTICOAGULANT_FACTS.dabigatran.reversal}.`, pearl:"Urgent reversal requires provider and protocol-directed management.", tags:["dabigatran","idarucizumab","reversal"] },
  { id:"ac-know-apixaban-class", category:"anticoagulants", subtype:"factor-xa-knowledge", difficulty:"beginner", title:"Apixaban Drug Class", scenario:"The medication list includes apixaban (Eliquis).", prompt:"Which mechanism best describes apixaban?", options:["Direct factor Xa inhibition","Direct thrombin inhibition","Vitamin K antagonism","Platelet COX inhibition"], correct:0, explanation:"Apixaban is a direct factor Xa inhibitor.", pearl:"Bleeding assessment and renal considerations remain important even without routine INR titration.", tags:["apixaban","Eliquis","factor Xa"] },
  { id:"ac-know-rivaroxaban-class", category:"anticoagulants", subtype:"factor-xa-knowledge", difficulty:"beginner", title:"Rivaroxaban Drug Class", scenario:"The medication record lists rivaroxaban (Xarelto).", prompt:"Which mechanism best describes rivaroxaban?", options:["Factor Xa inhibition","Thrombin activation","Vitamin K replacement","Platelet production stimulation"], correct:0, explanation:"Rivaroxaban is a direct factor Xa inhibitor.", pearl:"Verify the indication, dose, renal considerations, and bleeding risk.", tags:["rivaroxaban","Xarelto","factor Xa"] },
  { id:"ac-know-enoxaparin-class", category:"anticoagulants", subtype:"enoxaparin-knowledge", difficulty:"beginner", title:"Enoxaparin Classification", scenario:"The order lists enoxaparin (Lovenox).", prompt:"How is enoxaparin classified?", options:["Low-molecular-weight heparin","Vitamin K antagonist","Direct thrombin inhibitor","Thrombolytic"], correct:0, explanation:`Enoxaparin is a ${ANTICOAGULANT_FACTS.enoxaparin.class}.`, pearl:"Do not interchange enoxaparin dosing with unfractionated heparin dosing.", tags:["enoxaparin","Lovenox","LMWH"] },
  { id:"ac-know-enoxaparin-route", category:"anticoagulants", subtype:"enoxaparin-administration", difficulty:"beginner", title:"Enoxaparin Route", scenario:"An adult receives enoxaparin for VTE prophylaxis.", prompt:"Which route is expected for routine administration?", options:["Subcutaneous","Intramuscular","Sublingual","Inhaled"], correct:0, explanation:`Enoxaparin is given ${ANTICOAGULANT_FACTS.enoxaparin.route}.`, pearl:"Avoid intramuscular administration in an anticoagulated patient unless specifically directed.", tags:["enoxaparin","subcutaneous","administration"] },
  { id:"ac-know-hit-priority", category:"anticoagulants", subtype:"heparin-hit", difficulty:"intermediate", title:"Possible Heparin-Induced Thrombocytopenia", scenario:"A patient's platelet count falls substantially several days after starting heparin.", prompt:"Which complication should the nurse suspect and report promptly?", options:["Heparin-induced thrombocytopenia","Iron-deficiency anemia","Hyperglycemia","Pancreatitis"], correct:0, explanation:"A significant platelet decline during heparin exposure can signal HIT.", pearl:"HIT is a prothrombotic emergency. Stop-and-substitute decisions require immediate protocol-directed evaluation.", tags:["heparin","HIT","platelets","safety"], kind:"clinical-application" },
  { id:"ac-know-bleeding-sign", category:"anticoagulants", subtype:"anticoagulant-safety", difficulty:"beginner", title:"Bleeding Assessment", scenario:"A patient is receiving therapeutic anticoagulation.", prompt:"Which finding requires prompt bleeding evaluation?", options:["Black tarry stool","Clear urine","Warm dry skin","Pulse 72/min"], correct:0, explanation:"Melena can indicate gastrointestinal bleeding.", pearl:"Assess visible and occult bleeding, vital signs, and relevant laboratory trends.", tags:["bleeding","melena","safety"] },
  { id:"ac-know-heparin-rapid", category:"anticoagulants", subtype:"heparin-knowledge", difficulty:"beginner", title:"Rapid IV Heparin Effect", scenario:"An adult requires anticoagulation with a rapidly titratable IV medication.", prompt:"Which medication has a rapid IV effect and can be continuously infused?", options:["Unfractionated heparin","Warfarin","Oral vitamin K","Aspirin enteric coated"], correct:0, explanation:"IV unfractionated heparin has a rapid effect and can be titrated by protocol.", pearl:"Confirm bolus, concentration, units per hour, pump rate, and monitoring schedule.", tags:["heparin","IV","rapid effect","infusion"] },
  { id:"ac-know-warfarin-onset", category:"anticoagulants", subtype:"warfarin-knowledge", difficulty:"beginner", title:"Warfarin Onset", scenario:"A patient begins warfarin therapy.", prompt:"Which onset description is most accurate?", options:["Immediate within seconds","Delayed","Only active when given IV","No anticoagulant effect"], correct:1, explanation:`Warfarin has a ${ANTICOAGULANT_FACTS.warfarin.onset} onset because existing clotting factors must decline.`, pearl:"Do not assume an oral warfarin dose creates immediate therapeutic anticoagulation.", tags:["warfarin","delayed onset","safety"] },
  { id:"ac-know-warfarin-mechanism", category:"anticoagulants", subtype:"warfarin-knowledge", difficulty:"beginner", title:"Warfarin Mechanism", scenario:"The nurse explains why INR is monitored during warfarin therapy.", prompt:"Which mechanism describes warfarin?", options:["Vitamin K antagonist","Direct factor Xa inhibitor","Direct thrombin inhibitor","Platelet transfusion stimulant"], correct:0, explanation:ANTICOAGULANT_FACTS.warfarin.mechanism, pearl:"Medication and dietary interactions can change anticoagulant effect.", tags:["warfarin","vitamin K antagonist","mechanism"] },
  { id:"ac-know-lab-match", category:"anticoagulants", subtype:"anticoagulant-lab-association", difficulty:"intermediate", title:"Medication and Laboratory Match", scenario:"The nurse compares common monitoring associations.", prompt:"Which pairing is correct?", options:["Warfarin and aPTT only","IV unfractionated heparin and aPTT","Apixaban and routine INR titration","Enoxaparin and hemoglobin A1c"], correct:1, explanation:"aPTT is commonly used for IV unfractionated heparin protocols, while PT/INR monitors warfarin.", pearl:"Always follow the medication-specific and institution-specific monitoring plan.", tags:["heparin","warfarin","aPTT","INR"] },
  { id:"ac-know-high-aptt", category:"anticoagulants", subtype:"heparin-lab-interpretation", difficulty:"intermediate", title:"Supratherapeutic aPTT", scenario:"A patient on IV heparin has an aPTT above the protocol target and new oozing at the IV site.", prompt:"What is the nurse's priority?", options:["Increase the infusion without checking the protocol","Recognize bleeding risk and follow the heparin protocol","Give vitamin K independently","Ignore the result because aPTT is unrelated"], correct:1, explanation:"A high aPTT plus bleeding signs requires immediate protocol-guided action and escalation.", pearl:"Do not independently improvise heparin titration outside the ordered protocol.", tags:["heparin","aPTT","bleeding","protocol"], kind:"clinical-application" },
  { id:"ac-know-high-inr", category:"anticoagulants", subtype:"warfarin-lab-interpretation", difficulty:"intermediate", title:"High INR and Bleeding", scenario:"A patient taking warfarin has an INR above the ordered goal and reports nosebleeds.", prompt:"Which interpretation is most appropriate?", options:["Reduced bleeding risk","Possible excessive anticoagulation and bleeding risk","Expected glucose effect","Evidence of HIT"], correct:1, explanation:"An INR above the ordered therapeutic goal can reflect excessive anticoagulation.", pearl:"Hold or reversal decisions require the prescriber's order and current protocol.", tags:["warfarin","INR","bleeding","interpretation"], kind:"clinical-application" },
  { id:"ac-know-enoxaparin-uses", category:"anticoagulants", subtype:"enoxaparin-knowledge", difficulty:"beginner", title:"Enoxaparin Uses", scenario:"The nurse reviews indications for low-molecular-weight heparin.", prompt:"Which is a common use of enoxaparin?", options:["VTE prophylaxis","Treatment of hypoglycemia","Reversal of warfarin","Treatment of bacterial pneumonia"], correct:0, explanation:"Enoxaparin is commonly used for VTE prophylaxis and for treatment in appropriate DVT or PE scenarios.", pearl:"Prophylaxis and treatment regimens are not interchangeable.", tags:["enoxaparin","VTE prophylaxis","DVT","PE"] },
  { id:"ac-know-renal", category:"anticoagulants", subtype:"doac-safety", difficulty:"intermediate", title:"Renal Function and Anticoagulants", scenario:"An older adult with reduced renal function takes an oral anticoagulant.", prompt:"Which nursing action is appropriate?", options:["Ignore renal function","Verify renal function and the ordered regimen","Double the dose automatically","Replace the drug with warfarin without an order"], correct:1, explanation:"Renal function can affect exposure and dosing decisions for several anticoagulants.", pearl:"Do not make independent dose changes. Verify the order and escalate concerns.", tags:["renal function","DOAC","safety"] },
  { id:"ac-know-doac-inr", category:"anticoagulants", subtype:"doac-monitoring", difficulty:"intermediate", title:"DOAC Monitoring Concept", scenario:"A patient takes apixaban for an appropriate atrial fibrillation indication.", prompt:"Which statement is correct?", options:["Routine INR titration is used exactly like warfarin","Bleeding and renal function still require assessment","aPTT determines every outpatient dose","No medication reconciliation is needed"], correct:1, explanation:"Direct oral anticoagulants are not routinely titrated to INR like warfarin, but safety monitoring remains essential.", pearl:"Absence of routine INR titration does not mean absence of bleeding risk.", tags:["apixaban","DOAC","INR","monitoring"] },
  { id:"ac-know-af-use", category:"anticoagulants", subtype:"doac-indications", difficulty:"beginner", title:"Factor Xa Inhibitor Use", scenario:"An adult with appropriate non-valvular atrial fibrillation needs stroke-risk reduction.", prompt:"Which medication is a direct factor Xa inhibitor used in such scenarios?", options:["Apixaban","Protamine sulfate","Vitamin K","Regular insulin"], correct:0, explanation:"Apixaban is a direct factor Xa inhibitor used for stroke and systemic embolism risk reduction in appropriate patients.", pearl:"Confirm the indication and patient-specific contraindications before administration.", tags:["apixaban","atrial fibrillation","stroke prevention"] },
  { id:"ac-know-dabigatran-use", category:"anticoagulants", subtype:"dabigatran-knowledge", difficulty:"beginner", title:"Dabigatran Common Use", scenario:"The nurse reviews dabigatran therapy.", prompt:"Which is a common use in appropriate adults?", options:["Risk reduction for stroke and systemic embolism in non-valvular atrial fibrillation","Reversal of heparin","Treatment of hypoglycemia","Platelet transfusion"], correct:0, explanation:ANTICOAGULANT_FACTS.dabigatran.commonUse, pearl:"Verify renal function, bleeding risk, and the exact indication.", tags:["dabigatran","atrial fibrillation","stroke prevention"] },
  { id:"ac-know-safety-sata", category:"anticoagulants", subtype:"anticoagulant-safety", difficulty:"intermediate", title:"Anticoagulant Safety Assessment", scenario:"The nurse assesses a patient receiving anticoagulation.", prompt:"Which findings should be reported as possible bleeding? Select all that apply.", options:["Hematuria","Melena","New unexplained bruising","Stable appetite"], correct:[0,1,2], explanation:"Blood in urine, black tarry stool, and new unexplained bruising can indicate bleeding.", pearl:"Trend symptoms, vital signs, hemoglobin, and medication exposure together.", tags:["bleeding","hematuria","melena","select all"] },
  { id:"ac-know-hit-sata", category:"anticoagulants", subtype:"heparin-hit", difficulty:"advanced", title:"HIT Recognition", scenario:"A patient receiving heparin develops a substantial platelet decline and a new painful swollen leg.", prompt:"Which findings support concern for HIT? Select all that apply.", options:["Platelet decline","New thrombosis","Improved appetite","Recent heparin exposure"], correct:[0,1,3], explanation:"HIT concern increases with heparin exposure, platelet decline, and new thrombosis.", pearl:"HIT can cause thrombosis despite thrombocytopenia and requires urgent evaluation.", tags:["HIT","platelets","thrombosis","select all"] },
  { id:"ac-know-protamine-lmwh", category:"anticoagulants", subtype:"enoxaparin-reversal", difficulty:"advanced", title:"Enoxaparin Reversal Concept", scenario:"A patient has serious bleeding after enoxaparin.", prompt:"Which statement about protamine is most accurate?", options:["It provides complete reversal in every case","It can provide partial reversal","It is the reversal agent for warfarin","It increases factor Xa inhibition"], correct:1, explanation:ANTICOAGULANT_FACTS.enoxaparin.reversal, pearl:"LMWH reversal is incomplete and must follow time-sensitive protocol guidance.", tags:["enoxaparin","protamine","partial reversal"] },
  { id:"ac-know-platelets", category:"anticoagulants", subtype:"heparin-monitoring", difficulty:"beginner", title:"Platelet Monitoring", scenario:"A patient begins unfractionated heparin therapy.", prompt:"Which trend is particularly important for HIT surveillance?", options:["Platelet count","Hemoglobin A1c","Lipase","TSH"], correct:0, explanation:"Platelet trends help identify possible heparin-induced thrombocytopenia.", pearl:"Evaluate the magnitude and timing of platelet decline, not a single value alone.", tags:["heparin","platelets","HIT","monitoring"] },
  { id:"ac-know-warfarin-interaction", category:"anticoagulants", subtype:"warfarin-safety", difficulty:"intermediate", title:"Warfarin Interaction Safety", scenario:"A patient taking warfarin is prescribed a new medication.", prompt:"Which action is safest?", options:["Assume no interaction is possible","Review the medication for interaction and monitor as ordered","Stop warfarin permanently without an order","Skip medication reconciliation"], correct:1, explanation:"Many medications and changes in vitamin K intake can affect warfarin response.", pearl:"Report new prescriptions, over-the-counter products, and supplements for interaction review.", tags:["warfarin","interactions","safety"] },
  { id:"ac-know-im-injection", category:"anticoagulants", subtype:"anticoagulant-safety", difficulty:"intermediate", title:"Injection Bleeding Precaution", scenario:"A patient is therapeutically anticoagulated and an IM injection is considered.", prompt:"Which principle is appropriate?", options:["IM injections have no bleeding risk","Avoid unnecessary IM injections and verify the plan","Massage every injection site vigorously","Stop anticoagulation independently"], correct:1, explanation:"Intramuscular injections can increase local bleeding and hematoma risk.", pearl:"Use an alternative route when appropriate and ordered.", tags:["bleeding precautions","IM injection","safety"] },
  { id:"ac-know-heparin-routes", category:"anticoagulants", subtype:"heparin-knowledge", difficulty:"beginner", title:"Unfractionated Heparin Routes", scenario:"The nurse reviews common unfractionated heparin routes.", prompt:"Which routes are used?", options:["IV and subcutaneous","Oral and inhaled","Intranasal only","Topical only"], correct:0, explanation:"Unfractionated heparin may be administered IV or subcutaneously depending on the indication.", pearl:"Never substitute a route or concentration without a verified order.", tags:["heparin","IV","subcutaneous","route"] },
  { id:"ac-know-enoxaparin-hit", category:"anticoagulants", subtype:"enoxaparin-safety", difficulty:"intermediate", title:"LMWH Thrombocytopenia Concern", scenario:"A patient receiving enoxaparin develops a major platelet decline.", prompt:"Which action is appropriate?", options:["Dismiss the trend because LMWH cannot affect platelets","Report concern for heparin-associated thrombocytopenia","Give an extra dose","Change to IM administration"], correct:1, explanation:"LMWH still carries thrombocytopenia and HIT concerns.", pearl:"Escalate a significant platelet decline promptly.", tags:["enoxaparin","platelets","HIT","safety"] },
  { id:"ac-know-med-match", category:"anticoagulants", subtype:"anticoagulant-identification", difficulty:"intermediate", title:"Medication Class Match", scenario:"The nurse compares anticoagulant classes.", prompt:"Which pairing is correct?", options:["Dabigatran: direct thrombin inhibitor","Warfarin: direct factor Xa inhibitor","Apixaban: vitamin K antagonist","Heparin: oral DOAC"], correct:0, explanation:"Dabigatran directly inhibits thrombin.", pearl:"Class identification helps connect monitoring and reversal concepts.", tags:["dabigatran","warfarin","apixaban","class"] },
  { id:"ac-know-reversal-match", category:"anticoagulants", subtype:"anticoagulant-reversal", difficulty:"advanced", title:"Reversal Agent Match", scenario:"The nurse matches an anticoagulant with a reversal concept.", prompt:"Which pairing is correct?", options:["Unfractionated heparin: protamine sulfate","Warfarin: idarucizumab","Dabigatran: vitamin K","Enoxaparin: naloxone"], correct:0, explanation:"Protamine sulfate reverses unfractionated heparin. Vitamin K is used for warfarin, and idarucizumab reverses dabigatran.", pearl:"Reversal urgency and adjunct products depend on the clinical situation and protocol.", tags:["reversal","heparin","warfarin","dabigatran"] },
  { id:"ac-know-pump-safety", category:"anticoagulants", subtype:"heparin-infusion-safety", difficulty:"intermediate", title:"Heparin Pump Programming Safety", scenario:"The nurse prepares a continuous heparin infusion.", prompt:"Which values must be reconciled before starting the pump?", options:["Bag concentration, ordered units per hour, and calculated mL/hr","Only the patient's room number","Only the bag volume","Only the pump brand"], correct:0, explanation:"The concentration and ordered dose determine the pump rate.", pearl:"Independently verify units, concentration, patient weight when used, and mL/hr per policy.", tags:["heparin","infusion","pump","double check"] },
  { id:"ac-know-dose-types", category:"anticoagulants", subtype:"enoxaparin-knowledge", difficulty:"intermediate", title:"Enoxaparin Regimen Purpose", scenario:"The nurse compares prophylactic and treatment enoxaparin regimens.", prompt:"Which statement is correct?", options:["All indications use the same dose","Prophylaxis and treatment regimens can differ","Enoxaparin is never weight based","Enoxaparin is given orally"], correct:1, explanation:"Treatment dosing may be weight based, while prophylaxis commonly uses a different regimen.", pearl:"Verify the indication before evaluating whether a dose is appropriate.", tags:["enoxaparin","prophylaxis","treatment","weight based"] },
  { id:"ac-know-lab-priority", category:"anticoagulants", subtype:"anticoagulant-lab-association", difficulty:"advanced", title:"Monitoring Priority Comparison", scenario:"One patient receives IV unfractionated heparin and another takes warfarin.", prompt:"Which monitoring pair is correct?", options:["Heparin: aPTT protocol; warfarin: PT/INR","Heparin: INR only; warfarin: aPTT only","Both: hemoglobin A1c","Neither requires bleeding assessment"], correct:0, explanation:"IV heparin is commonly protocol-monitored with aPTT or anti-Xa, while warfarin uses PT/INR.", pearl:"Laboratory values complement, but never replace, assessment for bleeding.", tags:["heparin","warfarin","aPTT","INR"] },
  { id:"ac-know-no-peds", category:"anticoagulants", subtype:"adult-weight-based", difficulty:"intermediate", title:"Adult Weight-Based Anticoagulation", scenario:"An adult heparin protocol uses units/kg/hr.", prompt:"Which statement is appropriate?", options:["Adult weight-based dosing is a pediatric safe-dose-range question","Adult weight-based heparin calculations are appropriate MedMath practice","All adults receive the same infusion rate","Weight should be ignored"], correct:1, explanation:"Adult heparin protocols commonly require weight-based calculations.", pearl:"Use the protocol-specified dosing weight and units.", tags:["adult","weight based","heparin","scope"] },
];

function DABIGATRAN_CLASS(): string {
  return `Dabigatran is a ${ANTICOAGULANT_FACTS.dabigatran.class}.`;
}

export const medicationKnowledgeTemplates: QuestionTemplate[] = [
  ...insulinSpecs.map(makeKnowledgeTemplate),
  ...anticoagulantSpecs.map(makeKnowledgeTemplate),
];

export const MEDICATION_KNOWLEDGE_COUNTS = {
  insulin: insulinSpecs.length,
  anticoagulants: anticoagulantSpecs.length,
} as const;
