import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { ALL_QUESTION_TEMPLATES } from "../lib/medmath/templates/index.ts";
import { roundTo } from "../lib/medmath/rounding.ts";
import type { StoredNumericQuestion } from "../lib/medmath/types.ts";

const EXPECTED_QUESTION_COUNT = 277;

const rngOverrides: Record<string, number[]> = {
  // Required regression fixtures.
  "cc-milrinone-mcg-kg-min": [0.2, 0], // 70 kg, 0.25 mcg/kg/min
  "multi-magnesium-infusion-eclamp-rate": [0.6], // 1.5 g/hr, 20 g/500 mL
  "cc-reverse-norepi-mlhr-to-mcgkgmin": [0], // 15 mL/hr, 75 kg
  "iv-pump-ivpb-90min-vancomycin": [0], // 250 mL over 90 minutes
};

function deterministicRng(questionId: string): () => number {
  const values = rngOverrides[questionId] ?? [0];
  let index = 0;
  return () => values[index++] ?? values.at(-1) ?? 0;
}

function assertStoredQuestion(question: StoredNumericQuestion): void {
  if (!Number.isFinite(question.correctAnswer)) {
    throw new Error(
      `Missing or invalid correctAnswer for question ${question.id}: ${question.correctAnswer}`,
    );
  }
  if (question.correctAnswer === 0) {
    throw new Error(
      `Suspicious zero correctAnswer requires manual verification for question ${question.id}`,
    );
  }
  if (!question.answerUnit.trim()) {
    throw new Error(`Missing answerUnit for question ${question.id}`);
  }
  if (
    !Number.isInteger(question.answerPrecision) ||
    question.answerPrecision < 0
  ) {
    throw new Error(
      `Invalid answerPrecision for question ${question.id}: ${question.answerPrecision}`,
    );
  }
}

if (ALL_QUESTION_TEMPLATES.length !== EXPECTED_QUESTION_COUNT) {
  throw new Error(
    `Expected ${EXPECTED_QUESTION_COUNT} templates, found ${ALL_QUESTION_TEMPLATES.length}`,
  );
}

const storedQuestions: StoredNumericQuestion[] = ALL_QUESTION_TEMPLATES.map(
  (template) => {
    const generated = template.generate(deterministicRng(template.id));
    const question: StoredNumericQuestion = {
      id: template.id,
      category: template.category,
      subtype: template.subtype,
      difficulty: template.difficulty,
      title: template.title,
      clinicalContext: template.clinicalContext,
      ...generated,
      // Store the final answer at its declared grading precision.
      correctAnswer: roundTo(
        generated.correctAnswer,
        generated.answerPrecision,
      ),
    };

    assertStoredQuestion(question);
    return question;
  },
);

const ids = new Set(storedQuestions.map((question) => question.id));
if (ids.size !== storedQuestions.length) {
  throw new Error("Duplicate question IDs found while materializing MedMath bank");
}

const outputPath = fileURLToPath(
  new URL("../lib/medmath/question-bank.generated.ts", import.meta.url),
);
const contents = `/* eslint-disable */
// This file is generated by scripts/materialize-medmath-bank.ts.
// Do not calculate clinical answers in production code. Regenerate and audit this file instead.

import type { StoredNumericQuestion } from "./types.ts";

export const STORED_MEDMATH_QUESTIONS: StoredNumericQuestion[] = ${JSON.stringify(storedQuestions, null, 2)};
`;

await writeFile(outputPath, contents, "utf8");
console.log(
  `Materialized ${storedQuestions.length} verified-schema MedMath questions to ${outputPath}`,
);
